Repository Daniel-Assuncao89/helpr-front-jfs5, pull requests merged in 2022-12, with the labels that each got.

#50 adicionado modo noturno na aplicação
  angular.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/nav-bar/nav-bar.component.css
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/services/theme.service.ts
  src/app/shared/material/material.module.ts
  src/custom-theme.scss
Labels: enhancement

#51 troca do mecânismo de alert para toastr
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/services/auth.service.ts
  src/app/services/chamado.service.ts
  src/app/services/cliente.service.ts
  src/app/views/chamados/new-chamado/new-chamado.component.ts
  src/app/views/clientes/clientes/clientes.component.ts
  src/app/views/clientes/edit-cliente/edit-cliente.component.ts
  src/app/views/clientes/new-cliente/new-cliente.component.ts
  src/app/views/login/login/login.component.ts
  src/custom-theme.scss
Labels: enhancement

#52 Pagina de listar Futuros Clientes e service de Futuro Cliente
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futuro-cliente.ts
  src/app/services/futuro-cliente.service.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.css
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.ts
  src/assets/favicon.ico
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/assets/img/1.png
  src/assets/img/3.png
  src/assets/img/5.png
  src/assets/img/ext1.png
  src/assets/img/ext2.png
  src/assets/img/ext3.png
  src/assets/img/ext4.png
  src/assets/img/icons8-facebook-novo-24.png
  src/assets/img/icons8-instagram-24.png
  src/assets/img/icons8-linkedin-24.png
  src/assets/img/icons8-twitter-24.png
  src/assets/img/quad1.png
  src/assets/img/quad2.png
  src/assets/img/quad3.png
  src/assets/img/quad4.png
  src/assets/img/txt1.png
  src/assets/img/txt2.png
  src/assets/img/txt3.png
  src/assets/img/txt4.png
  src/assets/img/txt5.jpeg
Labels: enhancement

#53 Ajustes nas rotas
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futuro-cliente.ts
  src/app/services/futuro-cliente.service.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
Labels: bug

#56 Pagina para visualizar a relacao de funcionarios e cadastro.
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/funcionario.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.ts
Labels: enhancement

#57 criação de recurso de utilização de cookie para lembrar senha e e-mail no login
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/views/login/login/login.component.css
  src/app/views/login/login/login.component.html
  src/app/views/login/login/login.component.ts
Labels: enhancement

#58 Pagina FAQ - Dúvidas Frequentes
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/views/faq/faq-routing.module.ts
  src/app/views/faq/faq.module.ts
  src/app/views/faq/faq/faq.component.css
  src/app/views/faq/faq/faq.component.html
  src/app/views/faq/faq/faq.component.ts
  src/styles.css
Labels: enhancement

#59 Criacao de mascara para os campos de CPF e telefone
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
  src/app/views/clientes/new-cliente/new-cliente.component.html
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.html
Labels: bug, enhancement

#61 Criação de Caixa Dialog com propaganda em Carrocel
  package-lock.json
  src/app/views/login/login/login.component.css
  src/app/views/login/login/login.component.html
Labels: enhancement

#60 Visualização de candidatos
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futuro-candidato.ts
  src/app/services/futuro-candidato.service.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.css
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.html
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.ts
Labels: bug, enhancement

#62 Criado perfil do funcionário logado
  src/app/app.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/funcionario.ts
  src/app/services/auth.service.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.css
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.html
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.ts
Labels: enhancement

#63 Tratamento dos dados da foto para renderização
  package-lock.json
  package.json
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.css
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.html
Labels: enhancement

#64 Criado paginação nas tabelas da aplicação
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/chamados/chamados.component.ts
  src/app/views/clientes/clientes/clientes.component.html
  src/app/views/clientes/clientes/clientes.component.ts
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.html
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.ts
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#65 Implementacao de janela de diálogo para mostrar detalhes do cliente.
  package-lock.json
  src/app/components/components.module.ts
  src/app/components/details/details.component.css
  src/app/components/details/details.component.html
  src/app/components/details/details.component.ts
  src/app/views/clientes/clientes/clientes.component.css
  src/app/views/clientes/clientes/clientes.component.html
  src/app/views/clientes/clientes/clientes.component.ts
Labels: enhancement

#66 Correção de conflito.
  package-lock.json
  src/app/views/clientes/clientes/clientes.component.ts
Labels: bug

#67 Criação de caixa de detalhes na página Cargo
  src/app/app.module.ts
  src/app/components/components.module.ts
  src/app/components/details-cargo/details-cargo.component.css
  src/app/components/details-cargo/details-cargo.component.html
  src/app/components/details-cargo/details-cargo.component.ts
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
  src/app/views/clientes/clientes/clientes.component.ts
Labels: enhancement

#68 Criado compo de upload de foto de funcionário
  package-lock.json
  package.json
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.html
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionarios/new-funcionario.component.ts
Labels: enhancement

#69 Criação de dialog para detalhes de Chamados
  src/app/components/components.module.ts
  src/app/components/details-cargo/details-cargo.component.css
  src/app/components/details-cargo/details-cargo.component.html
  src/app/components/details-chamado/details-chamado.component.css
  src/app/components/details-chamado/details-chamado.component.html
  src/app/components/details-chamado/details-chamado.component.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/chamados/chamados.component.ts
Labels: enhancement

#70 Mudança da cor primária
  src/custom-theme.scss
  src/styles.css
Labels: enhancement

#71 Criação de Stepper para novo candidato
  src/app/components/components.module.ts
  src/app/components/details-cargo/details-cargo.component.html
  src/app/components/futuro-candidato/futuro-candidato.component.css
  src/app/components/futuro-candidato/futuro-candidato.component.html
  src/app/components/futuro-candidato/futuro-candidato.component.ts
  src/app/models/futuro-candidato.ts
  src/app/services/futuro-candidato.service.ts
  src/app/views/login/login/login.component.css
  src/app/views/login/login/login.component.html
  src/app/views/login/login/login.component.ts
Labels: enhancement

#73 Exclusão de Futuro candidato e cliente
  src/app/services/futuro-candidato.service.ts
  src/app/services/futuro-cliente.service.ts
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.html
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.ts
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.ts
Labels: enhancement

#74 Criação de novo cargo
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/cargos.module.ts
  src/app/views/cargos/new-cargo/new-cargo.component.css
  src/app/views/cargos/new-cargo/new-cargo.component.html
  src/app/views/cargos/new-cargo/new-cargo.component.ts
Labels: enhancement

#75 criado pipe para mostrar img padrão caso funcionário não tenha foto
  src/app/app.module.ts
  src/app/pipes/avatar.pipe.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.html
  src/assets/img/avatar.png
  src/assets/img/no-image.png
Labels: enhancement

#78 Padronização dos Títulos e Rotas da Aplicação
  src/app/app-routing.module.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/new-cargo/new-cargo.component.html
  src/app/views/chamados/chamados-routing.module.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/index.html
Labels: enhancement

#79 criado guards para role de admin e de funcionario
  src/app/app-routing.module.ts
  src/app/guards/admin.guard.ts
  src/app/guards/funcionario.guard.ts
  src/app/services/auth.service.ts
Labels: enhancement

#80 Implementação de spinner de carregamento.
  src/app/app.component.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#81 Criação de Footer para acesso ao FAQ
  package-lock.json
  package.json
  src/app/views/faq/faq/faq.component.html
  src/app/views/login/login/login.component.css
  src/app/views/login/login/login.component.html
Labels: enhancement

#83 arrumados alguns bugs e feito método de logout
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/models/cargo.ts
  src/app/services/auth.service.ts
  src/app/views/cargos/cargos/cargos.component.css
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/new-cargo/new-cargo.component.html
  src/app/views/cargos/new-cargo/new-cargo.component.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/clientes/clientes/clientes.component.html
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.html
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/meu-perfil/meu-perfil.component.ts
Labels: bug

#85 Implementação de spinner de carregamento na página de clientes
  src/app/views/clientes/clientes/clientes.component.html
  src/app/views/clientes/clientes/clientes.component.ts
Labels: enhancement

#87 arrumado falha na segurança das rotas
  src/app/app-routing.module.ts
Labels: bug

#89 Exclusão de conteudos desnecessarios
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.html
  src/app/views/clientes/futuro-clientes/futuro-clientes.component.html
  src/app/views/funcionarios/edit-funcionario/edit-funcionario.component.ts
Labels: bug

#88 Inclusão de texto explicativo e imagem na Página Home
  src/app/views/home/home/home.component.css
  src/app/views/home/home/home.component.html
Labels: enhancement

#90 Details para funcionario
  src/app/components/components.module.ts
  src/app/components/details-funcionario/details-funcionario.component.css
  src/app/components/details-funcionario/details-funcionario.component.html
  src/app/components/details-funcionario/details-funcionario.component.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#91 Aplicação do Spinner nas Páginas de Cargo e Chamado
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/chamados/chamados.component.ts
Labels: enhancement

#92 Criação do editar cargo
  src/app/models/cargo.ts
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/cargos.module.ts
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/edit-cargo/edit-cargo.component.css
  src/app/views/cargos/edit-cargo/edit-cargo.component.html
  src/app/views/cargos/edit-cargo/edit-cargo.component.ts
Labels: enhancement

#95 Dark mode bug
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/services/auth.service.ts
  src/app/services/theme.service.ts
  src/app/views/faq/faq/faq.component.html
  src/app/views/faq/faq/faq.component.ts
  src/app/views/home/home/home.component.css
  src/app/views/login/login/login.component.css
Labels: bug
